# Source this file in your shell for this project session.
export MEMSEARCH_PROVIDER="local"
export MEMSEARCH_MODEL="BAAI/bge-m3"
export PM="/Users/pranay/Projects/projects-memory"
export PROJECT_REL="pdf_editor"
export AGENT_DOCTRINE_ROOT="/Users/pranay/Projects/agent-start/doctrines"
export AGENT_DOCTRINE_SOURCE="/Users/pranay/Projects/agent-start/doctrines/OPERATING_DOCTRINE.md"
export AGENT_DOCTRINE_VERSION="8.1"
export AGENT_DOCTRINE_SHA256="c22b129bf41942d06c4a5c1eb4c7de96ce1669d471c4c35a50335d18fe9eb1ac"
export AGENT_DOCTRINE_MANIFEST="/Users/pranay/Projects/agent-start/doctrines/DOCTRINE_FAMILY_MANIFEST.json"
export AGENT_SELECTED_DOCTRINES="OPERATING_DOCTRINE.md"
export AGENT_SESSION_CONTEXT="/Users/pranay/Projects/pdf_editor/docs/context/agent-start/SESSION_CONTEXT.md"
export AGENT_KICKOFF_PROMPT="/Users/pranay/Projects/pdf_editor/docs/context/agent-start/AGENT_KICKOFF_PROMPT.txt"
