# Source this file in your shell for this project session.
export MEMSEARCH_PROVIDER="local"
export MEMSEARCH_MODEL="BAAI/bge-m3"
export PM="/Users/pranay/Projects/projects-memory"
export PROJECT_REL="pdf_editor"
export AGENT_DOCTRINE_ROOT="/Users/pranay/Projects/agent-start/doctrines"
export AGENT_DOCTRINE_SOURCE="/Users/pranay/Projects/agent-start/doctrines/OPERATING_DOCTRINE.md"
export AGENT_DOCTRINE_VERSION="8.1"
export AGENT_DOCTRINE_SHA256="3b3523ef815da1e87d923578976d45d90d13dbac1bd28cae452a3ea1e2105d90"
export AGENT_DOCTRINE_MANIFEST="/Users/pranay/Projects/agent-start/doctrines/DOCTRINE_FAMILY_MANIFEST.json"
export AGENT_SELECTED_DOCTRINES="OPERATING_DOCTRINE.md"
export AGENT_SESSION_CONTEXT="/Users/pranay/Projects/pdf_editor/docs/context/agent-start/SESSION_CONTEXT.md"
export AGENT_KICKOFF_PROMPT="/Users/pranay/Projects/pdf_editor/docs/context/agent-start/AGENT_KICKOFF_PROMPT.txt"
