import Foundation
import PDFKit
import Testing
@testable import PDFEditorCore

/// Multi-select listbox pipeline hardening (2026-09-06).
///
/// Extends the choice-field pipeline to `/FT /Ch` fields with the /Ff
/// multi-select bit (bit 22, value 2097152 = 1 << 21 — measured on pdf-lib
/// `AcroChoiceFlags.MultiSelect = flag(22 - 1)`). Per PDF 32000-1 §12.7.5.4
/// (Table 247) such fields carry:
///
/// - `/V` as an ARRAY of selected export strings (vs one string), and
/// - `/I` as the sorted option indices of the selection.
///
/// Fixtures live in `benchmark/datasets/choice-fixtures/` (generated by
/// `generate_choice_fixtures.py`, which now also emits them):
///
///    8. listbox_multi_presets.pdf       — array /V [Swift, Go], /I [0,3]
///    9. listbox_multi_pairs.pdf         — pair-form /Opt, array /V of exports
///   10. listbox_multi_empty.pdf         — bit 22 set, /V + /I absent
///   11. listbox_multi_hierarchical.pdf  — two dotted multi-select fields
///   12. listbox_single_select.pdf       — bit 22 CLEAR (negative control)
///
/// Measured viewer fact (2026-09-06, PDFKit on macOS 26): PDFKit reads
/// single-string /V through widgetStringValue but returns an EMPTY string
/// for array /V even on the pristine pikepdf-written fixture — the
/// multi-select ground truth is therefore structural (walkAcroForm) plus
/// the independent engines (qpdf bytes, pdf-lib model), and the PDFKit
/// cross-read here asserts the LIMITATION so a future macOS that starts
/// decoding array /V fails this test and updates the documented claim.
@Suite("GeneratedListboxFixtures")
struct GeneratedListboxFixtureTests {

    private static var projectRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
    }

    private static func fixtureURL(_ name: String) -> URL {
        URL(fileURLWithPath: projectRoot.path + "/benchmark/datasets/choice-fixtures/\(name)")
    }

    /// (file, field, options, isMultiSelect, singleV, arrayV, indices).
    /// `singleV` is the string /V when the selection is single/absent;
    /// `arrayV`+`indices` are the multi-select array shape. Matches the
    /// generator's `main()` exactly.
    static let fixtures: [(
        file: String, field: String, options: [String], isMultiSelect: Bool,
        singleV: String?, arrayV: [String], indices: [Int]
    )] = [
        ("listbox_multi_presets.pdf", "skills",
         ["Swift", "Python", "Rust", "Go", "Ruby"], true, nil, ["Swift", "Go"], [0, 3]),
        ("listbox_multi_pairs.pdf", "regions_multi",
         ["na", "emea", "apac", "latam"], true, nil, ["emea", "apac", "latam"], [1, 2, 3]),
        ("listbox_multi_empty.pdf", "addons",
         ["Backup", "Encryption", "Support"], true, nil, [], []),
        ("listbox_multi_hierarchical.pdf", "project.tags",
         ["core", "ui", "docs", "infra"], true, nil, ["core", "ui"], [0, 1]),
        ("listbox_multi_hierarchical.pdf", "project.reviewers",
         ["ada", "linus", "grace"], true, nil, ["grace"], [2]),
        ("listbox_single_select.pdf", "department",
         ["Eng", "Design", "Ops"], false, "Eng", [], []),
    ]

    // MARK: - Presence + structural read

    @Test("All generated listbox fixtures exist on disk")
    func fixturesPresent() {
        let files = Set(Self.fixtures.map(\.file))
        for file in files {
            #expect(
                FileManager.default.fileExists(atPath: Self.fixtureURL(file).path),
                "missing generated fixture \(file) — rerun benchmark/datasets/generate_choice_fixtures.py"
            )
        }
        #expect(files.count >= 5, "must have 5+ distinct listbox fixtures")
    }

    @Test("walkAcroForm decodes bit 22, array /V and /I for every listbox field")
    func structuralReadMatchesGenerator() throws {
        var checked = 0
        for fixture in Self.fixtures {
            let data = try Data(contentsOf: Self.fixtureURL(fixture.file))
            let nodes = try PDFIncrementalFormWriter.walkAcroForm(data)
            let field = nodes.filter {
                $0.fullyQualifiedName == fixture.field && $0.fieldType == "Ch"
            }
            #expect(field.count == 1, "\(fixture.file) \(fixture.field): exactly one /Ch node")
            guard let node = field.first else { continue }

            #expect(node.isMultiSelect == fixture.isMultiSelect,
                    "\(fixture.file) \(fixture.field): multi-select bit must be \(fixture.isMultiSelect)")
            #expect(node.optionValues == fixture.options,
                    "\(fixture.file) \(fixture.field): /Opt must decode as \(fixture.options)")
            #expect(node.value == fixture.singleV,
                    "\(fixture.file) \(fixture.field): scalar /V must be \(fixture.singleV ?? "nil"), got \(node.value ?? "nil")")
            #expect(node.values == fixture.arrayV,
                    "\(fixture.file) \(fixture.field): array /V must decode as \(fixture.arrayV), got \(node.values)")
            #expect(node.selectedIndices == fixture.indices,
                    "\(fixture.file) \(fixture.field): /I must decode as \(fixture.indices), got \(node.selectedIndices)")
            // Array /V never leaks into the scalar channel (and vice versa):
            // the two shapes stay observable separately.
            #expect(node.values.isEmpty || node.value == nil,
                    "\(fixture.file) \(fixture.field): array /V must not populate the scalar /V channel")
            checked += 1
        }
        #expect(checked == Self.fixtures.count, "must structurally verify every fixture row")
    }

    // MARK: - IncrementalWriter multi-select round-trips

    @Test("IncrementalWriter writes array /V + /I + bit 22 and structurally verifies")
    func multiValueRoundTrip() throws {
        // (fixture, field, requested values, expected indices)
        let cases: [(String, String, [String], [Int])] = [
            ("listbox_multi_presets.pdf", "skills", ["Rust", "Ruby"], [2, 4]),
            ("listbox_multi_presets.pdf", "skills", ["Swift", "Python", "Go"], [0, 1, 3]),
            ("listbox_multi_hierarchical.pdf", "project.reviewers", ["ada", "linus"], [0, 1]),
            ("listbox_multi_pairs.pdf", "regions_multi", ["na", "apac"], [0, 2]),
        ]
        var verified = 0
        for (file, field, values, expectedIndices) in cases {
            let data = try Data(contentsOf: Self.fixtureURL(file))
            let nodes = try PDFIncrementalFormWriter.walkAcroForm(data)
            let plan = try PDFIncrementalFormWriter.resolveMultiSelectEditPlan(
                nodes: nodes, targetFieldName: field, requestedValues: values, source: data)
            let updated = try PDFIncrementalFormWriter.incrementalFieldUpdate(
                data, edits: plan.objectEdits, newObjects: plan.newObjectBodies)

            let after = try PDFIncrementalFormWriter.walkAcroForm(updated)
            let node = try #require(after.first { $0.fullyQualifiedName == field })
            #expect(node.isMultiSelect, "\(field): bit 22 must survive the write")
            #expect(node.values == values,
                    "\(field): array /V must read back \(values), got \(node.values)")
            #expect(node.selectedIndices == expectedIndices,
                    "\(field): /I must read back \(expectedIndices), got \(node.selectedIndices)")
            #expect(node.value == nil, "\(field): multi write must leave the scalar channel empty")

            #expect(
                AcroFormParityExperiment.verifyMultiSelectStructurally(
                    data: updated, fieldName: field, expectedExports: values,
                    requireMultiBit: true),
                "\(file) \(field): structural verifier must accept the multi write")
            verified += 1
        }
        #expect(verified >= 4, "must round-trip 4+ multi-value writes")
    }

    @Test("IncrementalWriter singleton and empty multi-selection shapes match pdf-lib's measured encodings")
    func singletonAndEmptyShapes() throws {
        // Singleton: /V single string, /I gone (pdf-lib deletes /I for 1
        // selection — measured on updateSelectedIndices).
        let data = try Data(contentsOf: Self.fixtureURL("listbox_multi_presets.pdf"))
        let nodes = try PDFIncrementalFormWriter.walkAcroForm(data)
        let singletonPlan = try PDFIncrementalFormWriter.resolveMultiSelectEditPlan(
            nodes: nodes, targetFieldName: "skills", requestedValues: ["Python"], source: data)
        let singleton = try PDFIncrementalFormWriter.incrementalFieldUpdate(
            data, edits: singletonPlan.objectEdits, newObjects: singletonPlan.newObjectBodies)
        let sNode = try #require(
            try PDFIncrementalFormWriter.walkAcroForm(singleton).first { $0.fullyQualifiedName == "skills" })
        #expect(sNode.value == "Python", "singleton write must carry a scalar /V")
        #expect(sNode.values.isEmpty, "singleton write must NOT produce an array /V")
        #expect(sNode.selectedIndices.isEmpty, "singleton write must clear /I")

        // Empty: /V and /I removed (pdf-lib deletes /V for 0 selections).
        let emptyPlan = try PDFIncrementalFormWriter.resolveMultiSelectEditPlan(
            nodes: nodes, targetFieldName: "skills", requestedValues: [], source: data)
        let empty = try PDFIncrementalFormWriter.incrementalFieldUpdate(
            data, edits: emptyPlan.objectEdits, newObjects: emptyPlan.newObjectBodies)
        let eNode = try #require(
            try PDFIncrementalFormWriter.walkAcroForm(empty).first { $0.fullyQualifiedName == "skills" })
        #expect(eNode.value == nil && eNode.values.isEmpty, "empty write must leave no /V")
        #expect(eNode.selectedIndices.isEmpty, "empty write must leave no /I")
        #expect(eNode.isMultiSelect, "bit 22 must survive the empty write")
    }

    @Test("Multi-value write on a single-select listbox is refused (fail closed)")
    func singleSelectRefusesMulti() throws {
        let data = try Data(contentsOf: Self.fixtureURL("listbox_single_select.pdf"))
        let nodes = try PDFIncrementalFormWriter.walkAcroForm(data)
        #expect(throws: (any Error).self) {
            try PDFIncrementalFormWriter.resolveMultiSelectEditPlan(
                nodes: nodes, targetFieldName: "department",
                requestedValues: ["Design", "Ops"], source: data)
        }
        // Singleton writes stay legal on single-select listboxes.
        let plan = try PDFIncrementalFormWriter.resolveMultiSelectEditPlan(
            nodes: nodes, targetFieldName: "department", requestedValues: ["Design"], source: data)
        let updated = try PDFIncrementalFormWriter.incrementalFieldUpdate(
            data, edits: plan.objectEdits, newObjects: plan.newObjectBodies)
        let node = try #require(
            try PDFIncrementalFormWriter.walkAcroForm(updated).first { $0.fullyQualifiedName == "department" })
        #expect(node.value == "Design")
        #expect(!node.isMultiSelect, "single-select listbox must not gain bit 22")
    }

    @Test("Out-of-vocabulary requests are refused (fail closed)")
    func outOfVocabularyRefused() throws {
        let data = try Data(contentsOf: Self.fixtureURL("listbox_multi_presets.pdf"))
        let nodes = try PDFIncrementalFormWriter.walkAcroForm(data)
        #expect(throws: (any Error).self) {
            try PDFIncrementalFormWriter.resolveMultiSelectEditPlan(
                nodes: nodes, targetFieldName: "skills",
                requestedValues: ["Swift", "NotAnOption"], source: data)
        }
    }

    // MARK: - Viewer cross-read (measured limitation)

    @Test("PDFKit cross-read: singleton + single-select readable, array /V reads empty (measured limitation)")
    func pdfKitCrossRead() throws {
        // Singleton shape (scalar /V): PDFKit reads it through
        // widgetStringValue — this is the production read API.
        let data = try Data(contentsOf: Self.fixtureURL("listbox_multi_presets.pdf"))
        let nodes = try PDFIncrementalFormWriter.walkAcroForm(data)
        let plan = try PDFIncrementalFormWriter.resolveMultiSelectEditPlan(
            nodes: nodes, targetFieldName: "skills", requestedValues: ["Python"], source: data)
        let updated = try PDFIncrementalFormWriter.incrementalFieldUpdate(
            data, edits: plan.objectEdits, newObjects: plan.newObjectBodies)
        let tmp = NSTemporaryDirectory() + "genlb-\(UUID().uuidString).pdf"
        try updated.write(to: URL(fileURLWithPath: tmp))
        defer { try? FileManager.default.removeItem(atPath: tmp) }
        guard let doc = PDFDocument(url: URL(fileURLWithPath: tmp)) else {
            Issue.record("reopen failed after singleton write")
            return
        }
        var reads: [String] = []
        for p in 0..<doc.pageCount {
            guard let page = doc.page(at: p) else { continue }
            for a in page.annotations where a.fieldName == "skills" {
                reads.append(a.widgetStringValue ?? "")
            }
        }
        #expect(reads.contains("Python"),
                "PDFKit must read the singleton selection 'Python', saw \(reads)")

        // Array /V: PDFKit reads EMPTY even on the pristine pikepdf fixture
        // (measured 2026-09-06). Assert the limitation explicitly so a
        // future PDFKit that starts decoding array /V surfaces here and the
        // documented claim gets re-verified rather than silently drifting.
        let pristine = try Data(contentsOf: Self.fixtureURL("listbox_multi_presets.pdf"))
        let tmp2 = NSTemporaryDirectory() + "genlb-pristine-\(UUID().uuidString).pdf"
        try pristine.write(to: URL(fileURLWithPath: tmp2))
        defer { try? FileManager.default.removeItem(atPath: tmp2) }
        if let pristineDoc = PDFDocument(url: URL(fileURLWithPath: tmp2)) {
            var pristineReads: [String] = []
            for p in 0..<pristineDoc.pageCount {
                guard let page = pristineDoc.page(at: p) else { continue }
                for a in page.annotations where a.fieldName == "skills" {
                    pristineReads.append(a.widgetStringValue ?? "")
                }
            }
            #expect(pristineReads.allSatisfy { $0.isEmpty },
                    "MEASURED-LIMITATION DRIFT: PDFKit now decodes array /V (\(pristineReads)) — re-verify the multi-select cross-read claim and update this test + docs")
        }
    }

    // MARK: - Cross-engine: pdf-lib lane

    @Test("pdf-lib reads and writes multi-select listboxes (own model)")
    func pdfLibRoundTrip() throws {
        guard AcroFormExternalEngines.pdfLibAvailable else {
            Issue.record("pdf-lib lane not installed (npm install --prefix benchmark/acroform-lane)")
            return
        }
        let url = Self.fixtureURL("listbox_multi_presets.pdf")

        // Inspect: pdf-lib's PDFOptionList model must see the options.
        guard let report = AcroFormExternalEngines.pdfLibInspect(url.path),
              let field = (report.fields ?? []).first(where: { $0.name == "skills" && $0.type == "choice" })
        else {
            Issue.record("pdf-lib must detect skills as a choice field")
            return
        }
        #expect(Set(field.options ?? []) == Set(["Swift", "Python", "Rust", "Go", "Ruby"]),
                "pdf-lib options must match the /Opt vocabulary, saw \(field.options ?? [])")
        // The pristine array /V [Swift, Go] must surface in pdf-lib's
        // `values` channel (its getSelected() decodes array /V).
        #expect(Set(field.values ?? []) == Set(["Swift", "Go"]),
                "pdf-lib must read the pristine multi-selection, saw \(field.values ?? [])")

        // Write a 2-value selection through the choice_multi lane type and
        // read it back with pdf-lib's own model.
        let out = NSTemporaryDirectory() + "genlb-pdflib-\(UUID().uuidString).pdf"
        defer { try? FileManager.default.removeItem(atPath: out) }
        let selectionsJSON = "[\"Rust\",\"Go\"]"
        guard let write = AcroFormExternalEngines.pdfLibWrite(
            input: url.path, output: out,
            spec: [["name": "skills", "type": "choice_multi", "value": selectionsJSON]]),
            write.ok, (write.applied?.first { $0.name == "skills" })?.ok == true
        else {
            Issue.record("pdf-lib choice_multi write failed")
            return
        }
        guard let reread = AcroFormExternalEngines.pdfLibRead(out),
              let after = reread.fields?.first(where: { $0.name == "skills" })
        else {
            Issue.record("pdf-lib read-back failed")
            return
        }
        #expect(Set(after.values ?? []) == Set(["Rust", "Go"]),
                "pdf-lib must read its own multi-selection back, saw \(after.values ?? [])")

        // Structural ground truth on pdf-lib's output: bit 22 + array /V.
        let written = try Data(contentsOf: URL(fileURLWithPath: out))
        #expect(
            AcroFormParityExperiment.verifyMultiSelectStructurally(
                data: written, fieldName: "skills", expectedExports: ["Rust", "Go"],
                requireMultiBit: true),
            "pdf-lib's multi-select output must verify structurally (bit 22 + array /V)")
    }

    // MARK: - Diversity

    @Test("Listbox fixtures cover array/pair/empty/hierarchical/negative shapes")
    func fixtureDiversity() {
        #expect(Self.fixtures.contains { $0.isMultiSelect && $0.arrayV.count >= 2 },
                "2+ value array /V must be covered")
        #expect(Self.fixtures.contains { $0.isMultiSelect && $0.arrayV.count == 1 },
                "singleton array /V (via hierarchical reviewers) must be covered")
        #expect(Self.fixtures.contains { $0.file == "listbox_multi_pairs.pdf" },
                "pair-form /Opt multi-select must be covered")
        #expect(Self.fixtures.contains { $0.file == "listbox_multi_empty.pdf" },
                "empty multi-selection (no /V, no /I) must be covered")
        #expect(Self.fixtures.contains { !$0.isMultiSelect },
                "single-select negative control must be covered")
        let dotted = Self.fixtures.map(\.field).filter { $0.contains(".") }
        #expect(dotted.count >= 2, "hierarchical multi-select names must be covered")
    }
}
